<?php

use App\Models\Category;
use App\Models\ContentItem;
use App\Models\Course;
use App\Models\Enquiry;
use App\Models\Exam;
use App\Models\Package;
use App\Models\Question;
use App\Models\QuestionOption;
use App\Models\Subject;
use App\Models\User;

return [
    'categories' => [
        'label' => 'Categories',
        'model' => Category::class,
        'route_label' => 'categories',
        'icon' => 'layers',
        'sort' => 'name',
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'slug', 'label' => 'Slug'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => 'nullable|string|max:255', 'unique' => true, 'source' => 'name'],
            ['key' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
        ],
    ],
    'subjects' => [
        'label' => 'Subjects',
        'model' => Subject::class,
        'route_label' => 'subjects',
        'icon' => 'book-open',
        'sort' => 'name',
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'category.name', 'label' => 'Category'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['key' => 'category_id', 'label' => 'Category', 'type' => 'select', 'rules' => 'required|exists:categories,id', 'source_model' => Category::class, 'source_label' => 'name'],
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => 'nullable|string|max:255', 'unique' => true, 'source' => 'name'],
            ['key' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
        ],
    ],
    'courses' => [
        'label' => 'Courses',
        'model' => Course::class,
        'route_label' => 'courses',
        'icon' => 'graduation-cap',
        'sort' => 'title',
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'category.name', 'label' => 'Category'],
            ['field' => 'subject.name', 'label' => 'Subject'],
            ['field' => 'level', 'label' => 'Level'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['key' => 'category_id', 'label' => 'Category', 'type' => 'select', 'rules' => 'required|exists:categories,id', 'source_model' => Category::class, 'source_label' => 'name'],
            ['key' => 'subject_id', 'label' => 'Subject', 'type' => 'select', 'rules' => 'nullable|exists:subjects,id', 'source_model' => Subject::class, 'source_label' => 'name'],
            ['key' => 'title', 'label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'slug', 'label' => 'Slug', 'type' => 'text', 'rules' => 'nullable|string|max:255', 'unique' => true, 'source' => 'title'],
            ['key' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'level', 'label' => 'Level', 'type' => 'select', 'rules' => 'required|in:beginner,intermediate,advanced', 'options' => ['beginner' => 'Beginner', 'intermediate' => 'Intermediate', 'advanced' => 'Advanced']],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
        ],
    ],
    'packages' => [
        'label' => 'Packages',
        'model' => Package::class,
        'route_label' => 'packages',
        'icon' => 'package',
        'sort' => 'price',
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'price', 'label' => 'Price'],
            ['field' => 'duration_days', 'label' => 'Days'],
            ['field' => 'exam_limit', 'label' => 'Exam Limit'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'price', 'label' => 'Price', 'type' => 'number', 'rules' => 'required|numeric|min:0'],
            ['key' => 'duration_days', 'label' => 'Duration Days', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'exam_limit', 'label' => 'Exam Limit', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'features', 'label' => 'Features', 'type' => 'tags', 'rules' => 'nullable|array'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
        ],
    ],
    'exams' => [
        'label' => 'Exams',
        'model' => Exam::class,
        'route_label' => 'exams',
        'icon' => 'clipboard-list',
        'sort' => 'start_at',
        'direction' => 'desc',
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'course.title', 'label' => 'Course'],
            ['field' => 'exam_type', 'label' => 'Type'],
            ['field' => 'question_count', 'label' => 'Questions'],
            ['field' => 'is_published', 'label' => 'Published'],
        ],
        'fields' => [
            ['key' => 'course_id', 'label' => 'Course', 'type' => 'select', 'rules' => 'required|exists:courses,id', 'source_model' => Course::class, 'source_label' => 'title'],
            ['key' => 'title', 'label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'exam_type', 'label' => 'Exam Type', 'type' => 'select', 'rules' => 'required|in:practice,mock,live,audio', 'options' => ['practice' => 'Practice', 'mock' => 'Mock', 'live' => 'Live', 'audio' => 'Audio']],
            ['key' => 'duration_minutes', 'label' => 'Duration Minutes', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'total_marks', 'label' => 'Total Marks', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'pass_mark', 'label' => 'Pass Mark', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'question_count', 'label' => 'Question Count', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'start_at', 'label' => 'Start At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
            ['key' => 'end_at', 'label' => 'End At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
            ['key' => 'random_questions', 'label' => 'Random Questions', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
            ['key' => 'random_options', 'label' => 'Random Options', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
            ['key' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
        ],
    ],
    'audio-exams' => [
        'label' => 'Audio Practice',
        'model' => Exam::class,
        'route_label' => 'audio-exams',
        'icon' => 'headphones',
        'sort' => 'start_at',
        'direction' => 'desc',
        'where' => [
            'exam_type' => 'audio',
        ],
        'defaults' => [
            'exam_type' => 'audio',
        ],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'course.title', 'label' => 'Course'],
            ['field' => 'duration_minutes', 'label' => 'Minutes'],
            ['field' => 'question_count', 'label' => 'Questions'],
            ['field' => 'is_published', 'label' => 'Published'],
        ],
        'fields' => [
            ['key' => 'course_id', 'label' => 'Course', 'type' => 'select', 'rules' => 'required|exists:courses,id', 'source_model' => Course::class, 'source_label' => 'title'],
            ['key' => 'title', 'label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'exam_type', 'label' => 'Exam Type', 'type' => 'select', 'rules' => 'required|in:audio', 'options' => ['audio' => 'Audio']],
            ['key' => 'duration_minutes', 'label' => 'Duration Minutes', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'total_marks', 'label' => 'Total Marks', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'pass_mark', 'label' => 'Pass Mark', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'question_count', 'label' => 'Question Count', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'start_at', 'label' => 'Start At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
            ['key' => 'end_at', 'label' => 'End At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
            ['key' => 'random_questions', 'label' => 'Random Questions', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
            ['key' => 'random_options', 'label' => 'Random Options', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
            ['key' => 'is_published', 'label' => 'Published', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
        ],
    ],
    'questions' => [
        'label' => 'Questions',
        'model' => Question::class,
        'route_label' => 'questions',
        'icon' => 'help-circle',
        'sort' => 'created_at',
        'direction' => 'desc',
        'columns' => [
            ['field' => 'exam.title', 'label' => 'Exam'],
            ['field' => 'type', 'label' => 'Type'],
            ['field' => 'difficulty_level', 'label' => 'Difficulty'],
            ['field' => 'marks', 'label' => 'Marks'],
        ],
        'fields' => [
            ['key' => 'exam_id', 'label' => 'Exam', 'type' => 'select', 'rules' => 'required|exists:exams,id', 'source_model' => Exam::class, 'source_label' => 'title'],
            ['key' => 'course_id', 'label' => 'Course', 'type' => 'select', 'rules' => 'nullable|exists:courses,id', 'source_model' => Course::class, 'source_label' => 'title'],
            ['key' => 'type', 'label' => 'Type', 'type' => 'select', 'rules' => 'required|in:mcq,listening,reading,writing,image', 'options' => ['mcq' => 'MCQ', 'listening' => 'Listening', 'reading' => 'Reading', 'writing' => 'Writing', 'image' => 'Image']],
            ['key' => 'prompt', 'label' => 'Prompt', 'type' => 'textarea', 'rules' => 'required|string'],
            ['key' => 'explanation', 'label' => 'Explanation', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'difficulty_level', 'label' => 'Difficulty', 'type' => 'select', 'rules' => 'required|in:easy,medium,hard', 'options' => ['easy' => 'Easy', 'medium' => 'Medium', 'hard' => 'Hard']],
            ['key' => 'marks', 'label' => 'Marks', 'type' => 'number', 'rules' => 'required|integer|min:1'],
            ['key' => 'audio_url', 'label' => 'Audio URL', 'type' => 'text', 'rules' => 'nullable|string|max:255'],
            ['key' => 'image_url', 'label' => 'Image URL', 'type' => 'text', 'rules' => 'nullable|string|max:255'],
        ],
    ],
    'question-options' => [
        'label' => 'Question Options',
        'model' => QuestionOption::class,
        'route_label' => 'question-options',
        'icon' => 'list',
        'sort' => 'sort_order',
        'columns' => [
            ['field' => 'question.prompt', 'label' => 'Question'],
            ['field' => 'label', 'label' => 'Label'],
            ['field' => 'is_correct', 'label' => 'Correct'],
        ],
        'fields' => [
            ['key' => 'question_id', 'label' => 'Question', 'type' => 'select', 'rules' => 'required|exists:questions,id', 'source_model' => Question::class, 'source_label' => 'prompt'],
            ['key' => 'label', 'label' => 'Label', 'type' => 'text', 'rules' => 'required|string|max:10'],
            ['key' => 'text', 'label' => 'Text', 'type' => 'textarea', 'rules' => 'required|string'],
            ['key' => 'is_correct', 'label' => 'Correct Answer', 'type' => 'boolean', 'rules' => 'nullable|boolean'],
            ['key' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'rules' => 'required|integer|min:0'],
        ],
    ],
    'enquiries' => [
        'label' => 'Enquiries',
        'model' => Enquiry::class,
        'route_label' => 'enquiries',
        'icon' => 'message-circle',
        'sort' => 'created_at',
        'direction' => 'desc',
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'subject', 'label' => 'Subject'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'fields' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:120'],
            ['key' => 'email', 'label' => 'Email', 'type' => 'text', 'rules' => 'required|email|max:180'],
            ['key' => 'subject', 'label' => 'Subject', 'type' => 'text', 'rules' => 'required|string|max:160'],
            ['key' => 'message', 'label' => 'Message', 'type' => 'textarea', 'rules' => 'required|string'],
            ['key' => 'category_id', 'label' => 'Category', 'type' => 'select', 'rules' => 'nullable|exists:categories,id', 'source_model' => Category::class, 'source_label' => 'name'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:open,pending,solved', 'options' => ['open' => 'Open', 'pending' => 'Pending', 'solved' => 'Solved']],
            ['key' => 'teacher_reply', 'label' => 'Teacher Reply', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'replied_at', 'label' => 'Replied At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
        ],
    ],
    'content-items' => [
        'label' => 'Mobile Content',
        'model' => ContentItem::class,
        'route_label' => 'content-items',
        'icon' => 'sparkles',
        'sort' => 'section',
        'columns' => [
            ['field' => 'section', 'label' => 'Section'],
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'sort_order', 'label' => 'Sort'],
        ],
        'fields' => [
            ['key' => 'section', 'label' => 'Section', 'type' => 'select', 'rules' => 'required|string|max:80', 'options' => [
                'dashboard_stats' => 'Dashboard Stats',
                'notifications' => 'Notifications',
                'results' => 'Results',
                'leaderboard' => 'Leaderboard',
                'gallery' => 'Gallery',
                'bookmarks' => 'Bookmarks',
                'streak' => 'Streak',
                'certificates' => 'Certificates',
                'profile_badges' => 'Profile Badges',
                'weekly_progress' => 'Weekly Progress',
                'menu_shortcuts' => 'Menu Shortcuts',
            ]],
            ['key' => 'title', 'label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'subtitle', 'label' => 'Subtitle', 'type' => 'text', 'rules' => 'nullable|string|max:255'],
            ['key' => 'body', 'label' => 'Body', 'type' => 'textarea', 'rules' => 'nullable|string'],
            ['key' => 'metadata', 'label' => 'Metadata JSON', 'type' => 'json', 'rules' => 'nullable|string'],
            ['key' => 'status', 'label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ['key' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'rules' => 'required|integer|min:0'],
            ['key' => 'published_at', 'label' => 'Published At', 'type' => 'datetime-local', 'rules' => 'nullable|date'],
        ],
    ],
    'users' => [
        'label' => 'Users',
        'model' => User::class,
        'route_label' => 'users',
        'icon' => 'users',
        'sort' => 'name',
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'email', 'label' => 'Email'],
            ['field' => 'role', 'label' => 'Role'],
            ['field' => 'phone', 'label' => 'Phone'],
        ],
        'fields' => [
            ['key' => 'name', 'label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:255'],
            ['key' => 'email', 'label' => 'Email', 'type' => 'text', 'rules' => 'required|email|max:255'],
            ['key' => 'password', 'label' => 'Password', 'type' => 'text', 'rules' => 'nullable|string|min:8'],
            ['key' => 'role', 'label' => 'Role', 'type' => 'select', 'rules' => 'required|in:admin,teacher,student', 'options' => ['admin' => 'Admin', 'teacher' => 'Teacher', 'student' => 'Student']],
            ['key' => 'phone', 'label' => 'Phone', 'type' => 'text', 'rules' => 'nullable|string|max:40'],
        ],
    ],
];
